### ISSUE TITLE
[Colors & Styles] Logos

### ISSUE THREAD

**Issue by mfpekala** [Ameelio/react-native-ameelio-library#1]
Download logos into the project and expose a single <Logo /> component that can take in props to display our logo.

## Tasks

- [ ] Download the variants listed in the figma
- [ ] Create a component that can specify which variant to use easily
- [ ] Create styling props so it can be used dynamically
