### ISSUE TITLE
[Cards] Thumbnails

### ISSUE THREAD

**Issue by toriqiu** [Ameelio/react-native-ameelio-library#12]
<img width="503" alt="Screen Shot 2021-08-20 at 9 45 07 AM" src="https://user-images.githubusercontent.com/50127470/130251155-31a59d48-d731-47ef-8a89-5fc83cdcaf8f.png">
Update fonts, shadows, and colors for thumbnail cards

## Tasks

- [ ] card/thumbnail/large
- [ ] card/thumbnail/nohorizscroll/one-one
- [ ] card/thumbnail/nohorizscroll/two-one
- [ ] card/thumbnail/nohorizscroll/nohorizscroll
- [ ] card/thumbnail/nohorizscroll

## Related Issues

https://www.figma.com/file/4EMXrcthXd1CwZYBik3uGz/V1-Rebrand-of-Mobile-Design-Library-(August-2021)?node-id=946%3A58470
