### ISSUE TITLE
[Cards] Two-line cards with header

### ISSUE THREAD

**Issue by toriqiu** [Ameelio/react-native-ameelio-library#13]
<img width="284" alt="Screen Shot 2021-08-20 at 9 49 20 AM" src="https://user-images.githubusercontent.com/50127470/130251714-4e242a40-f182-411e-9849-d0b4f06054f3.png">
Update font, shadows, and colors for cards with headers 

## Tasks

- [x] card/two-line/small/HeaderEmphasis
- [x] card/two-line/small/HeaderSmallHeader
- [x] card/two-line/small/BodyHeader

## Related Issues

https://www.figma.com/file/4EMXrcthXd1CwZYBik3uGz/V1-Rebrand-of-Mobile-Design-Library-(August-2021)?node-id=946%3A58469
