### ISSUE TITLE
[Alerts & Notifications] Alert normal

### ISSUE THREAD

**Issue by toriqiu** [Ameelio/react-native-ameelio-library#16]
<img width="521" alt="Screen Shot 2021-08-20 at 10 02 00 AM" src="https://user-images.githubusercontent.com/50127470/130253442-ced19a69-f393-4a1a-8eb0-226079313bd1.png">

## Tasks

- [ ] .mother/alert/normal/close
- [ ] .mother/alert/normal/seemore
- [ ] .mother/alert/normal/close

## Related Issues

https://www.figma.com/file/4EMXrcthXd1CwZYBik3uGz/V1-Rebrand-of-Mobile-Design-Library-(August-2021)?node-id=958%3A56166
