### ISSUE TITLE
[Alerts & Notifications] Toast

### ISSUE THREAD

**Issue by toriqiu** [Ameelio/react-native-ameelio-library#17]
<img width="520" alt="Screen Shot 2021-08-20 at 10 03 29 AM" src="https://user-images.githubusercontent.com/50127470/130253608-be740591-b4e6-4939-9e46-59433b24948d.png">

## Tasks

- [x] .mother/alert/toast/error
- [x] .mother/alert/toast/warning
- [x] .mother/alert/toast/success

## Related Issues

https://www.figma.com/file/4EMXrcthXd1CwZYBik3uGz/V1-Rebrand-of-Mobile-Design-Library-(August-2021)?node-id=958%3A56166
