### ISSUE TITLE
[Alerts & Notifications] Tooltip

### ISSUE THREAD

**Issue by toriqiu** [Ameelio/react-native-ameelio-library#18]
<img width="331" alt="Screen Shot 2021-08-20 at 10 06 10 AM" src="https://user-images.githubusercontent.com/50127470/130253929-55322a70-be13-44a6-ad2f-5dddbb54f345.png">

Update `src/UserInput/Tooltip.react.tsx` to support the new designs (position of the tail on the speech bubble changes). Use `storybook/stories/UserInput/Tooltip.stories.tsx` to test the new designs.

## Tasks

- [ ] .mother/informational/tooltip/AppearsTopRight
- [ ] .mother/informational/tooltip/AppearsTopLeft
- [ ] .mother/informational/tooltip/AppearsTopCenter
- [ ] .mother/informational/tooltip/AppearsBotLeft
- [ ] .mother/informational/tooltip/AppearsBotRight
- [ ] .mother/informational/tooltip/AppearsBotCenter

## Related Issues

https://www.figma.com/file/4EMXrcthXd1CwZYBik3uGz/V1-Rebrand-of-Mobile-Design-Library-(August-2021)?node-id=958%3A56166
