### ISSUE TITLE
[Controls & Inputs] Buttons

### ISSUE THREAD

**Issue by toriqiu** [Ameelio/react-native-ameelio-library#19]
<img width="437" alt="Screen Shot 2021-08-20 at 12 02 51 PM" src="https://user-images.githubusercontent.com/50127470/130268664-60a64ad7-5dd3-4fdb-a52e-24c314c0bee5.png">

## Tasks

- [ ] .mother/button/container/standard
- [ ] .mother/container/tertiary
- [ ] .mother/button/container/small

## Related Issues

https://www.figma.com/file/4EMXrcthXd1CwZYBik3uGz/V1-Rebrand-of-Mobile-Design-Library-(August-2021)?node-id=944%3A51375
