### ISSUE TITLE
[Controls & Inputs] Button Containers

### ISSUE THREAD

**Issue by toriqiu** [Ameelio/react-native-ameelio-library#26]
<img width="382" alt="Screen Shot 2021-08-25 at 10 40 23 PM" src="https://user-images.githubusercontent.com/50127470/130896847-8f55ad82-d83e-4c4c-8865-c3aa1678fbe2.png">

## Tasks

- [x] button/container/standard
- [x] button/container-pair/standard
- [x] button/container/floating
- [x] button/container/small

## Related Issues

https://www.figma.com/file/4EMXrcthXd1CwZYBik3uGz/V1-Rebrand-of-Mobile-Design-Library-(August-2021)?node-id=948%3A50936
