### ISSUE TITLE
[Controls & Inputs] Pricing

### ISSUE THREAD

**Issue by toriqiu** [Ameelio/react-native-ameelio-library#28]
<img width="394" alt="Screen Shot 2021-08-25 at 10 49 15 PM" src="https://user-images.githubusercontent.com/50127470/130897566-95529c7f-9a6f-47b9-b699-80f6ca1722cb.png">

## Tasks

- [x] pricing/free-credit
- [x] pricing/free-credit
- [ ] pricing/plus-banner
- [x] pricing/your-balance
- [x] TransactionFrame/RectSelectWithPicture (should be updated already in `letters-mobile`)

## Related Issues

https://www.figma.com/file/4EMXrcthXd1CwZYBik3uGz/V1-Rebrand-of-Mobile-Design-Library-(August-2021)?node-id=952%3A54101
