### ISSUE TITLE
[Colors & Styles] Typography

### ISSUE THREAD

**Issue by mfpekala** [Ameelio/react-native-ameelio-library#3]
Export text components that mirror the figma and provide specified text formats.

## Tasks

- [x] Download and properly link the required fonts
- [x] Custom header component which accepts a `size` prop.
- [x] Custom body component which accepts `size` and `bold` props
- [x] Custom caption component which accepts a `size` prop
- [x] dynamic words component which accepts `type = 'semi-bold' | 'regular' | 'medium' | 'semi-bold-italic'`, `fontSize` and can be used for the `Other` category on the figma so we don't have to make all those really small components with like one use case
