### ISSUE TITLE
[Design Components] Buttons

### ISSUE THREAD

**Issue by mfpekala** [Ameelio/react-native-ameelio-library#6]
Reusable button component!

## Tasks

- [ ] Use correct color / shadow / border stylings
- [ ] Accept `text` prop (or figure out how to use children)
- [ ] Accept `onPress` prop
- [ ] Accept `secondary` prop if secondary style applies
- [ ] Accept `border` prop if border should show up (only affects secondary style)
- [ ] Accept `contract` prop if it is not supposed to fill width
- [ ] Accept `style` prop to override any styles on the container / positioning 
- [ ] Accept `blocking` prop
- [ ] Accept `enabled` prop
