### ISSUE TITLE
[Design Components] Letters Mobile Navigation Bars

### ISSUE THREAD

**Issue by mfpekala** [Ameelio/react-native-ameelio-library#7]
Implement the new navigation styles (top and bottom) for letters mobile tabs + screens

## Tasks

- [ ] Update the Selected / unselected stylings in the tab bar.
- [ ] Implement the little bar with the contact that you can change
- [ ] Implement the little bar with username and ameelios / coins
- [ ] Implement the little contact bar with metrics
